# Generated by Django 4.2.5 on 2023-10-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
