# Generated by Django 4.2.5 on 2023-10-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctormodel',
            old_name='name',
            new_name='username',
        ),
    ]
